In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Uncleaned_DS_jobs.csv')
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [ ]:
df.tail()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
667,667,Data Scientist,$105K-$167K (Glassdoor est.),Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
668,668,Data Scientist,$105K-$167K (Glassdoor est.),Job Description\nBecome a thought leader withi...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
669,669,Data Scientist,$105K-$167K (Glassdoor est.),Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1
670,670,Data Scientist,$105K-$167K (Glassdoor est.),100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1
671,671,Data Scientist,$105K-$167K (Glassdoor est.),Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              672 non-null    int64
 1   Job Title          672 non-null    object
 2   Salary Estimate    672 non-null    object
 3   Job Description    672 non-null    object
 4   Rating             672 non-null    float64
 5   Company Name       672 non-null    object
 6   Location           672 non-null    object
 7   Headquarters       672 non-null    object
 8   Size               672 non-null    object
 9   Founded            672 non-null    int64
 10  Type of ownership  672 non-null    object
 11  Industry           672 non-null    object
 12  Sector             672 non-null    object
 13  Revenue            672 non-null    object
 14  Competitors        672 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 78.9+ KB

In [ ]:
df.shape

(672, 15)

In [ ]:
print((df == '-1').sum().to_string())

index                  0
Job Title              0
Salary Estimate        0
Job Description        0
Rating                 0
Company Name           0
Location               0
Headquarters          31
Size                  27
Founded                0
Type of ownership     27
Industry              71
Sector                71
Revenue               27
Competitors          501

In [ ]:
print((df == -1).sum().to_string())

index                  0
Job Title              0
Salary Estimate        0
Job Description        0
Rating                50
Company Name           0
Location               0
Headquarters           0
Size                   0
Founded              118
Type of ownership      0
Industry               0
Sector                 0
Revenue                0
Competitors            0

In [ ]:
import numpy as np

df.replace([-1, '-1'], np.nan, inplace=True)

In [ ]:
#Conting of NAs
print(df.isna().sum())

index                  0
Job Title              0
Salary Estimate        0
Job Description        0
Rating                50
Company Name           0
Location               0
Headquarters          31
Size                  27
Founded              118
Type of ownership     27
Industry              71
Sector                71
Revenue               27
Competitors          501
dtype: int64

In [ ]:
df

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993.0,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968.0,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),NaN
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981.0,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),NaN
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000.0,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998.0,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K (Glassdoor est.),Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989.0,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,NaN
668,668,Data Scientist,$105K-$167K (Glassdoor est.),Job Description\nBecome a thought leader withi...,NaN,JKGT,"San Francisco, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
669,669,Data Scientist,$105K-$167K (Glassdoor est.),Join a thriving company that is changing the w...,NaN,AccessHope,"Irwindale, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,670,Data Scientist,$105K-$167K (Glassdoor est.),100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,NaN,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),NaN
671,671,Data Scientist,$105K-$167K (Glassdoor est.),Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976.0,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),NaN

In [ ]:
#cleaning of job titles

def job_title(title):
  title_lower = title.lower()
  if 'data scientist' in title_lower:
    return 'Data scientist'
  elif 'data engineer' in title_lower:
    return 'Data engineer'
  elif 'analyst' in title_lower:
    return 'Analyst'
  elif 'machine learning' in title_lower:
    return 'MLE'
  elif 'manager' in title_lower:
    return 'Manager'
  elif 'director' in title_lower:
    return 'Director'
  else:
    return 'na'

df['Updated Job Title'] = df['Job Title'].apply(job_title)

In [ ]:
#List of the most common job types
df['Updated Job Title'].value_counts()

Updated Job Title
Data scientist    455
na                 69
Analyst            55
Data engineer      47
MLE                36
Manager             7
Director            3
Name: count, dtype: int64

In [ ]:
# Salary Estimate Columns
sorted(df['Salary Estimate'].unique())

['$101K-$165K (Glassdoor est.)',
 '$105K-$167K (Glassdoor est.)',
 '$110K-$163K (Glassdoor est.)',
 '$112K-$116K (Glassdoor est.)',
 '$122K-$146K (Glassdoor est.)',
 '$124K-$198K (Glassdoor est.)',
 '$128K-$201K (Glassdoor est.)',
 '$137K-$171K (Glassdoor est.)',
 '$138K-$158K (Glassdoor est.)',
 '$141K-$225K (Glassdoor est.)',
 '$145K-$225K(Employer est.)',
 '$212K-$331K (Glassdoor est.)',
 '$31K-$56K (Glassdoor est.)',
 '$56K-$97K (Glassdoor est.)',
 '$66K-$112K (Glassdoor est.)',
 '$69K-$116K (Glassdoor est.)',
 '$71K-$123K (Glassdoor est.)',
 '$75K-$131K (Glassdoor est.)',
 '$79K-$106K (Glassdoor est.)',
 '$79K-$131K (Glassdoor est.)',
 '$79K-$133K (Glassdoor est.)',
 '$79K-$147K (Glassdoor est.)',
 '$80K-$132K (Glassdoor est.)',
 '$87K-$141K (Glassdoor est.)',
 '$90K-$109K (Glassdoor est.)',
 '$90K-$124K (Glassdoor est.)',
 '$91K-$150K (Glassdoor est.)',
 '$92K-$155K (Glassdoor est.)',
 '$95K-$119K (Glassdoor est.)',
 '$99K-$132K (Glassdoor est.)']

In [ ]:
#removing 'Employer est.' and 'Glassdoor est.'
df['Salary Estimate'] = df['Salary Estimate'].apply(lambda x:x.replace('(Employer est.)','').replace(' (Glassdoor est.)','').replace('$',''))
sorted(df['Salary Estimate'].unique())

['101K-165K',
 '105K-167K',
 '110K-163K',
 '112K-116K',
 '122K-146K',
 '124K-198K',
 '128K-201K',
 '137K-171K',
 '138K-158K',
 '141K-225K',
 '145K-225K',
 '212K-331K',
 '31K-56K',
 '56K-97K',
 '66K-112K',
 '69K-116K',
 '71K-123K',
 '75K-131K',
 '79K-106K',
 '79K-131K',
 '79K-133K',
 '79K-147K',
 '80K-132K',
 '87K-141K',
 '90K-109K',
 '90K-124K',
 '91K-150K',
 '92K-155K',
 '95K-119K',
 '99K-132K']

In [ ]:
# Remove letter K, and multiply values with 1000

def salary_estimate(values):
    df = values.replace('K','')
    data2 = df.split('-')
    data3 = [str(int(datas)*1000) for datas in data2]
    return '-'.join(data3)

df['Salary Estimate'] =  df['Salary Estimate'].apply(salary_estimate)

sorted(df['Salary Estimate'].unique())

['101000-165000',
 '105000-167000',
 '110000-163000',
 '112000-116000',
 '122000-146000',
 '124000-198000',
 '128000-201000',
 '137000-171000',
 '138000-158000',
 '141000-225000',
 '145000-225000',
 '212000-331000',
 '31000-56000',
 '56000-97000',
 '66000-112000',
 '69000-116000',
 '71000-123000',
 '75000-131000',
 '79000-106000',
 '79000-131000',
 '79000-133000',
 '79000-147000',
 '80000-132000',
 '87000-141000',
 '90000-109000',
 '90000-124000',
 '91000-150000',
 '92000-155000',
 '95000-119000',
 '99000-132000']

In [ ]:
# Adding columna 'min_salary','max_salary', and 'avg_salary'

df['Min Salary'] = df['Salary Estimate'].apply(lambda x: int(x.split('-')[0]))
df['Max Salary'] = df['Salary Estimate'].apply(lambda x: int(x.split('-')[1]))
# Calculate average salary
df['Average Salary'] = (df['Min Salary'] + df['Max Salary']) / 2
df['Average Salary'] = df['Average Salary'].astype(int)

In [ ]:
sorted(df['Company Name'].unique())

['1-800-Flowers\n2.7',
 '1010data\n3.1',
 '10x Genomics\n4.2',
 '1904labs\n4.7',
 '22nd Century Technologies\n3.7',
 '7Park Data\n3.9',
 'A Place for Mom\n2.7',
 'A-Line Staffing Solutions\n4.1',
 'ABIOMED\n4.1',
 'ALTA IT Services\n3.9',
 'ASRC Federal Holding Company\n3.4',
 'AccessHope',
 'Acuity Insurance\n4.8',
 'Advance Sourcing Concepts\n3.4',
 'Advanced Bio-Logic Solutions Corp\n4.0',
 'Advanced BioScience Laboratories\n2.7',
 'Adwait Algorithm\n4.4',
 'AeroVironment\n4.2',
 'Affinity Solutions\n2.9',
 'AgreeYa Solutions\n3.8',
 'Alaka`ina Foundation Family of Companies\n3.6',
 'Alector\n4.8',
 'Alignment Healthcare\n3.5',
 'Alion Science & Technology\n3.6',
 'Allen Institute\n3.5',
 'AllianceBernstein\n3.2',
 'Allied Solutions\n3.4',
 'Altus Group\n3.7',
 'Americo Life\n3.3',
 'Ameritas Life Insurance Corp\n3.0',
 'Amyris\n3.3',
 'Analysis Group\n3.8',
 'Apex Systems\n3.9',
 'AppLovin\n4.8',
 'Apple\n4.1',
 'Applied Research Laboratories\n3.8',
 'Aptive\n3.5',
 'Argo Group US\n3.5',
 'Arsenal Biosciences\n5.0',
 'AstraZeneca\n4.0',
 'Autodesk\n4.0',
 'Averity\n5.0',
 'Aveshka, Inc.\n3.8',
 'Avlino\n4.9',
 'Axiologic Solutions\n4.5',
 'B4Corp',
 'BWX Technologies\n3.3',
 'Battelle\n3.1',
 'Bayside Solutions\n3.1',
 'Bayview Asset Management\n3.7',
 'Benson Hill\n3.5',
 'Berico Technologies',
 'Better Hire\n4.0',
 'Big Huge Games\n4.9',
 'Biogen\n3.6',
 'Blackstone Talent Group\n3.5',
 'Blend360\n4.6',
 'Blue Cloak LLC',
 'Blue Cross and Blue Shield of North Carolina\n3.7',
 'Blue Horizon Tek Solutions\n5.0',
 'Blue Icy Water, LLC',
 'Booz Allen Hamilton Inc.\n3.7',
 'Brighthouse Financial\n3.8',
 'Brillient\n3.9',
 'Buckman\n3.5',
 'Burns & McDonnell\n3.8',
 'C3.ai\n4.7',
 'CACI International\n3.5',
 'CIA\n3.8',
 'CRS Group\n4.7',
 'Cambridge Associates, LLC\n3.1',
 'Cambridge FX\n3.5',
 'Cambridge Mobile Telematics\n4.9',
 'Capio Group\n4.1',
 'CaptiveAire\n4.1',
 'CareDx\n2.5',
 'Carolina Power & Light Co\n3.7',
 'Caterpillar\n3.7',
 'Cenlar\n2.6',
 'Centauri\n4.6',
 'Central Business Solutions, Inc\n3.0',
 'Central California Alliance for Health\n3.5',
 'Centraprise\n4.2',
 'ChaTeck Incorporated\n5.0',
 'Change Healthcare\n2.7',
 'Chef\n3.6',
 'Child Care Aware of America\n2.8',
 'Clear Ridge Defense',
 'ClearEdge\n4.0',
 'Cohere Health\n5.0',
 'Colony Brands\n3.7',
 'Comcast\n3.5',
 'Community Behavioral Health\n3.6',
 'Compass Consulting Group\n4.7',
 'Comprehensive Healthcare\n2.6',
 'CompuForce',
 'Comtech Global Inc\n4.0',
 'Conagen\n2.0',
 'Concerto HealthAI\n3.3',
 'Conch Technologies, Inc\n4.6',
 'Conflux Systems Inc.\n4.5',
 'Constant Contact\n3.6',
 'ConsumerTrack\n3.2',
 "Cook Children's Health Care System\n3.8",
 'Coverent\n4.1',
 'Covid-19 Search Partners',
 'Creative Circle\n3.6',
 'Criteo\n3.9',
 'Criterion Systems, Inc.\n3.8',
 'Crossover Health\n3.5',
 'Crown Bioscience\n2.4',
 'Cubic\n3.3',
 'CyberCoders\n4.2',
 'DCS Corp\n4.1',
 'DW Simpson\n4.2',
 'DataLab USA\n3.6',
 'Demandbase\n4.5',
 'Dermalogica\n3.8',
 'Descript\n4.3',
 'Dice.com\n3.4',
 'Direct Agents\n4.4',
 'Dolphin\n3.5',
 'Dynetics\n4.0',
 'E3 Federal Solutions\n4.5',
 'EGlobalTech\n3.7',
 'Edmunds.com\n3.4',
 'Eliassen Group\n4.4',
 'Encode, Inc.',
 'Enterprise Solutions Inc\n3.8',
 'Envision Healthcare\n2.9',
 'Envision LLC\n4.5',
 'Eversight\n4.2',
 'Evidation\n4.1',
 'Evidera\n3.8',
 'Evolve Vacation Rental\n3.5',
 'Evolvinc',
 'Exact Sciences Corporation\n4.0',
 'Expedition Technology, Inc.\n5.0',
 'Exponent\n3.5',
 'FHLBank Pittsburgh\n3.8',
 'FM Systems\n3.4',
 'Falcon IT & Staffing Solutions',
 "Farmer's Business Network, Inc.\n3.5",
 'First Health Group\n3.2',
 'Fleetcor\n3.7',
 'Formation\n2.8',
 'Foundation Medicine\n4.0',
 'Fullpower Technologies, Inc.\n4.5',
 'GNS Healthcare\n2.9',
 'GSK\n3.9',
 'Gallup\n4.1',
 'Gap Inc.\n3.5',
 'Genentech\n4.0',
 'General Dynamics Information Technology\n3.4',
 'Genesis Research\n5.0',
 'Geotab\n4.3',
 'GetWellNetwork\n4.8',
 'Gigya\n3.6',
 'Giving Assistant\n4.8',
 'Global Data Management Inc\n4.5',
 'GovTech\n3.7',
 'GrainBridge, LLC',
 'Great-Circle Technologies\n2.2',
 'GreatAmerica Financial Services\n4.6',
 'Grid Dynamics\n4.0',
 'Group O\n3.1',
 'Guardian Life\n3.5',
 'GutCheck\n3.8',
 'Guzman & Griffin Technologies (GGTI)\n4.4',
 'HAN IT Staffing Inc.\n4.6',
 'HG Insights\n4.2',
 'HP Inc.\n4.1',
 'HPOne\n3.5',
 'Hackensack Meridian Health\n3.3',
 'Hatch Data Inc',
 'Healthfirst\n3.1',
 'Hexagon US Federal\n2.7',
 'HireAi',
 'Hive (CA)\n2.1',
 'Homology Medicines, Inc.\n4.4',
 'Huxley\n3.3',
 'IBM\n3.7',
 'ICW Group\n3.3',
 'IFG Companies\n2.9',
 'II-VI Incorporated\n3.3',
 'IMG Systems\n3.2',
 'INFICON\n3.5',
 'ISO New England\n3.8',
 'ISYS Technologies, Inc.\n3.6',
 'IT Concepts\n4.8',
 'IZEA\n4.2',
 'Indigo Slate\n3.0',
 'Infinitive Inc\n3.4',
 'Inland Empire Health Plan\n3.3',
 'Insider Inc\n3.3',
 'Insight Enterprises, Inc.\n4.2',
 'Intellectual Ventures\n3.3',
 'IntelliPro Group Inc.\n4.1',
 'Inter-American Development Bank\n3.5',
 'Intuit - Data\n4.4',
 'InvenTech Info\n4.8',
 'Itlize Global\n4.6',
 'JCD Staffing\n5.0',
 'JKGT',
 'Jacobs\n3.6',
 'Jane Street\n4.8',
 'Jobot\n5.0',
 'Joby Aviation\n4.3',
 'Johns Hopkins University Applied Physics Laboratory\n4.5',
 'Juniper Networks\n3.8',
 'KeHE Distributors\n2.5',
 'Kehe Food Distributors',
 'Kelly\n3.4',
 'Kforce\n4.1',
 'Kibo',
 'Kingfisher Systems\n4.5',
 'Klaviyo\n4.8',
 'Knowesis Inc.\n4.4',
 'Kognetics\n3.6',
 'Kollasoft Inc.\n3.2',
 'LSQ\n4.2',
 'Latitude, Inc.\n4.1',
 'Lawrence Livermore National Lab\n4.7',
 'Leidos\n3.5',
 'Lendio\n4.9',
 'Liberty Mutual Insurance\n3.4',
 'Life360\n3.9',
 'LifeOmic\n5.0',
 'Lightspeed Systems\n4.3',
 'LinQuest\n3.9',
 'Lorven Technologies Inc\n4.0',
 'MILVETS Systems Technology, Inc.\n3.4',
 'MIT Lincoln Laboratory\n3.8',
 'MITRE\n3.3',
 'Mackin\n3.4',
 'Magna International Inc.\n3.5',
 'ManTech\n4.2',
 'Market America Inc\n4.0',
 'Mars\n3.9',
 'MassMutual\n3.7',
 'Mathematica Policy Research\n3.4',
 'Maven Wave Partners\n4.5',
 'Maxar Technologies\n3.5',
 'Maxiom\n5.0',
 'Mentor Graphics\n4.1',
 'Meridian Knowledge Solutions\n4.4',
 'Merrick Bank\n3.6',
 'Metromile\n3.8',
 'Metronome, LLC\n3.2',
 'Microagility',
 'Midland Credit Management\n3.3',
 'MoTek Technologies\n3.1',
 'Monte Rosa Therapeutics',
 'Montway Inc\n3.4',
 'Moxie Software\n3.0',
 'Mteq\n3.7',
 'Murray Resources\n4.6',
 'NAVEX Global\n3.3',
 'NYSTEC\n3.8',
 'Natera\n3.9',
 'Navio',
 'Navy Federal Credit Union\n3.9',
 'Net2Source Inc.\n3.2',
 'Netskope\n4.0',
 'New England Biolabs\n4.9',
 'New Iron Group, Inc.\n5.0',
 'New Relic\n4.7',
 'New York Technology Partners\n4.0',
 'Noblis\n4.0',
 'Nolij Consulting\n3.9',
 'Notion Labs\n5.0',
 'Novartis\n3.9',
 'Novetta\n4.5',
 'Ntrepid\n4.2',
 'NuWave Solutions\n4.4',
 'Numeric, LLC\n3.2',
 'Object Partners\n4.7',
 'Offerpad\n4.4',
 'Old World Industries\n3.1',
 'OneMagnify\n4.4',
 'Opendoor\n3.6',
 'OppLoans\n4.4',
 'Oshkosh Corporation\n4.2',
 'Ovative Group\n4.3',
 'Oversight Systems\n4.7',
 'PETADATA',
 'PNNL\n3.7',
 'PROPRIUS\n5.0',
 'Pacific Northwest National Laboratory\n3.7',
 'Pactera Edge',
 'Paige\n5.0',
 'Parker Hannifin\n3.3',
 'PayPal\n3.8',
 'PeopleCom\n5.0',
 'Peraton\n3.4',
 'Perspecta\n3.2',
 'Pfizer\n4.1',
 'Phantom AI\n5.0',
 'Phoenix Operations Group\n5.0',
 'Photon Infotech\n3.0',
 'Plymouth Rock Assurance\n3.4',
 'Point72 Ventures',
 'Postmates - Corporate HQ\n3.2',
 'Powertek\n3.6',
 'Pragmatics, Inc.\n2.9',
 'Praxis Engineering\n4.7',
 'Predictive Research Inc\n3.9',
 'Procore Technologies\n4.2',
 'Progress Rail, A Caterpillar Company\n2.8',
 'Protolabs\n3.7',
 'Puget Sound Energy\n3.3',
 'PulsePoint\n4.3',
 'QOMPLX\n3.5',
 'Quartet Health\n3.9',
 'Quest Integrity\n2.9',
 'Quick Base\n4.3',
 'Qurate Retail Group\n3.6',
 'REE\n5.0',
 'Radiant Digital\n4.5',
 'Radical Convergence',
 'Rainmaker Resources, LLC',
 'Rapid Value Solutions\n3.9',
 'Relativity\n3.7',
 'Resurgent Capital Services\n4.4',
 'Reynolds American\n3.3',
 'Rincon Research Corporation\n4.2',
 'Ritedose\n3.5',
 'Riverside Research Institute\n3.6',
 'Robert Half\n3.5',
 'Roche\n4.1',
 'Rocket Lawyer\n4.4',
 'Royce Geospatial\n5.0',
 'Rubius Therapeutics\n3.8',
 'SAIC\n3.7',
 'SPECTRUM\n2.9',
 'SSATI\n5.0',
 'Sage Intacct\n4.7',
 'Sandhills Global\n2.7',
 'Sandia National Laboratories\n3.8',
 'Sanofi\n3.7',
 'Scoop\n4.7',
 'Security Finance Corporation of Spartanburg\n3.1',
 'Shape Security\n4.1',
 'Sharpedge Solutions Inc\n4.7',
 'Shelter Insurance\n4.1',
 'Shimento, Inc.\n2.9',
 'ShorePoint\n4.5',
 'SkillSoniq\n5.0',
 'SleePare\n3.4',
 'Smith Hanley Associates\n4.5',
 'Software Engineering Institute\n2.6',
 'SolutionIT, Inc.\n4.4',
 'Solving IT International Inc\n3.4',
 'Sonde Health',
 'Sophinea',
 'Southwest Research Institute\n3.9',
 'Spectrum Communications and Consulting\n3.4',
 'Sprezzatura Management Consulting',
 'Spring Health\n3.6',
 'State of Virginia\n3.2',
 'Stratagem Group\n4.4',
 'Stride Search',
 'Stripe\n4.0',
 'Summa Health System\n3.7',
 'Surya Systems\n4.6',
 'Swiss Re\n3.8',
 'Systems & Technology Research\n4.5',
 'T. Rowe Price\n3.6',
 'TA Digital\n3.7',
 'TACG Solutions\n4.5',
 'TBWA\\Chiat\\Day\n2.7',
 'TE Connectivity\n3.6',
 'TECHNOCRAFT Solutions\n3.4',
 'TRANZACT\n3.6',
 'Take-Two\n3.7',
 'Takeda\n3.7',
 'TechProjects\n4.8',
 'Tecolote Research\n3.8',
 'Temboo\n3.9',
 'Tempo Automation\n3.3',
 'Tempus Labs\n3.3',
 'The Buffalo Group\n4.3',
 'The Davey Tree Expert Company\n3.3',
 'The Drive Media, Inc.\n5.0',
 'The Knot Worldwide\n3.5',
 'The Mom Project\n4.9',
 'The Trade Desk\n3.2',
 'ThreeBridge Solutions\n3.5',
 'Thumbtack\n3.9',
 'Tivity Health\n3.2',
 'Tokio Marine HCC\n3.3',
 'Tower Health\n3.5',
 'Trace Data\n3.9',
 'TransVoyant\n3.0',
 'Travelers\n4.0',
 'Trexquant Investment\n4.0',
 'Trident Systems Inc\n3.4',
 'Triplebyte\n3.2',
 'Trovetechs Inc',
 'TrueAccord\n3.4',
 'Twitch\n3.6',
 'Twitter\n4.1',
 'Two95 International Inc.\n4.0',
 'Tygart Technology, Inc\n4.7',
 'US Pharmacopeia\n3.2',
 'USAC\n2.7',
 'USI\n3.4',
 'UST Global\n4.2',
 'Underwriters Laboratories\n3.3',
 'Unicom Technologies INC\n4.7',
 'United BioSource\n2.3',
 'Upside Business Travel\n4.1',
 'Upstart\n4.2',
 'VANTA Partners\n5.0',
 'VBeyond Corporation\n4.4',
 'Via Transportation\n3.7',
 'Visionary Integration Professionals\n4.3',
 'Visionist, Inc.\n4.9',
 'Voice\n3.4',
 'WCG (WIRB-Copernicus Group)\n3.6',
 'WGSN\n3.5',
 'Werner Enterprises Inc\n3.1',
 'Western Digital\n3.5',
 'XPO Logistics\n3.7',
 'XSELL Technologies\n3.6',
 'Xator Corporation\n2.9',
 'bioMérieux\n4.2',
 'eBay\n3.5',
 'hc1\n2.9',
 'iRobot\n3.5',
 'iSeatz\n3.5',
 'webfx.com\n4.7']

In [ ]:
#Cleaning of company name
df['Company Name'] = df['Company Name'].replace(r'\n\d\.\d', '', regex=True)

sorted(df['Company Name'].unique())

['1-800-Flowers',
 '1010data',
 '10x Genomics',
 '1904labs',
 '22nd Century Technologies',
 '7Park Data',
 'A Place for Mom',
 'A-Line Staffing Solutions',
 'ABIOMED',
 'ALTA IT Services',
 'ASRC Federal Holding Company',
 'AccessHope',
 'Acuity Insurance',
 'Advance Sourcing Concepts',
 'Advanced Bio-Logic Solutions Corp',
 'Advanced BioScience Laboratories',
 'Adwait Algorithm',
 'AeroVironment',
 'Affinity Solutions',
 'AgreeYa Solutions',
 'Alaka`ina Foundation Family of Companies',
 'Alector',
 'Alignment Healthcare',
 'Alion Science & Technology',
 'Allen Institute',
 'AllianceBernstein',
 'Allied Solutions',
 'Altus Group',
 'Americo Life',
 'Ameritas Life Insurance Corp',
 'Amyris',
 'Analysis Group',
 'Apex Systems',
 'AppLovin',
 'Apple',
 'Applied Research Laboratories',
 'Aptive',
 'Argo Group US',
 'Arsenal Biosciences',
 'AstraZeneca',
 'Autodesk',
 'Averity',
 'Aveshka, Inc.',
 'Avlino',
 'Axiologic Solutions',
 'B4Corp',
 'BWX Technologies',
 'Battelle',
 'Bayside Solutions',
 'Bayview Asset Management',
 'Benson Hill',
 'Berico Technologies',
 'Better Hire',
 'Big Huge Games',
 'Biogen',
 'Blackstone Talent Group',
 'Blend360',
 'Blue Cloak LLC',
 'Blue Cross and Blue Shield of North Carolina',
 'Blue Horizon Tek Solutions',
 'Blue Icy Water, LLC',
 'Booz Allen Hamilton Inc.',
 'Brighthouse Financial',
 'Brillient',
 'Buckman',
 'Burns & McDonnell',
 'C3.ai',
 'CACI International',
 'CIA',
 'CRS Group',
 'Cambridge Associates, LLC',
 'Cambridge FX',
 'Cambridge Mobile Telematics',
 'Capio Group',
 'CaptiveAire',
 'CareDx',
 'Carolina Power & Light Co',
 'Caterpillar',
 'Cenlar',
 'Centauri',
 'Central Business Solutions, Inc',
 'Central California Alliance for Health',
 'Centraprise',
 'ChaTeck Incorporated',
 'Change Healthcare',
 'Chef',
 'Child Care Aware of America',
 'Clear Ridge Defense',
 'ClearEdge',
 'Cohere Health',
 'Colony Brands',
 'Comcast',
 'Community Behavioral Health',
 'Compass Consulting Group',
 'Comprehensive Healthcare',
 'CompuForce',
 'Comtech Global Inc',
 'Conagen',
 'Concerto HealthAI',
 'Conch Technologies, Inc',
 'Conflux Systems Inc.',
 'Constant Contact',
 'ConsumerTrack',
 "Cook Children's Health Care System",
 'Coverent',
 'Covid-19 Search Partners',
 'Creative Circle',
 'Criteo',
 'Criterion Systems, Inc.',
 'Crossover Health',
 'Crown Bioscience',
 'Cubic',
 'CyberCoders',
 'DCS Corp',
 'DW Simpson',
 'DataLab USA',
 'Demandbase',
 'Dermalogica',
 'Descript',
 'Dice.com',
 'Direct Agents',
 'Dolphin',
 'Dynetics',
 'E3 Federal Solutions',
 'EGlobalTech',
 'Edmunds.com',
 'Eliassen Group',
 'Encode, Inc.',
 'Enterprise Solutions Inc',
 'Envision Healthcare',
 'Envision LLC',
 'Eversight',
 'Evidation',
 'Evidera',
 'Evolve Vacation Rental',
 'Evolvinc',
 'Exact Sciences Corporation',
 'Expedition Technology, Inc.',
 'Exponent',
 'FHLBank Pittsburgh',
 'FM Systems',
 'Falcon IT & Staffing Solutions',
 "Farmer's Business Network, Inc.",
 'First Health Group',
 'Fleetcor',
 'Formation',
 'Foundation Medicine',
 'Fullpower Technologies, Inc.',
 'GNS Healthcare',
 'GSK',
 'Gallup',
 'Gap Inc.',
 'Genentech',
 'General Dynamics Information Technology',
 'Genesis Research',
 'Geotab',
 'GetWellNetwork',
 'Gigya',
 'Giving Assistant',
 'Global Data Management Inc',
 'GovTech',
 'GrainBridge, LLC',
 'Great-Circle Technologies',
 'GreatAmerica Financial Services',
 'Grid Dynamics',
 'Group O',
 'Guardian Life',
 'GutCheck',
 'Guzman & Griffin Technologies (GGTI)',
 'HAN IT Staffing Inc.',
 'HG Insights',
 'HP Inc.',
 'HPOne',
 'Hackensack Meridian Health',
 'Hatch Data Inc',
 'Healthfirst',
 'Hexagon US Federal',
 'HireAi',
 'Hive (CA)',
 'Homology Medicines, Inc.',
 'Huxley',
 'IBM',
 'ICW Group',
 'IFG Companies',
 'II-VI Incorporated',
 'IMG Systems',
 'INFICON',
 'ISO New England',
 'ISYS Technologies, Inc.',
 'IT Concepts',
 'IZEA',
 'Indigo Slate',
 'Infinitive Inc',
 'Inland Empire Health Plan',
 'Insider Inc',
 'Insight Enterprises, Inc.',
 'Intellectual Ventures',
 'IntelliPro Group Inc.',
 'Inter-American Development Bank',
 'Intuit - Data',
 'InvenTech Info',
 'Itlize Global',
 'JCD Staffing',
 'JKGT',
 'Jacobs',
 'Jane Street',
 'Jobot',
 'Joby Aviation',
 'Johns Hopkins University Applied Physics Laboratory',
 'Juniper Networks',
 'KeHE Distributors',
 'Kehe Food Distributors',
 'Kelly',
 'Kforce',
 'Kibo',
 'Kingfisher Systems',
 'Klaviyo',
 'Knowesis Inc.',
 'Kognetics',
 'Kollasoft Inc.',
 'LSQ',
 'Latitude, Inc.',
 'Lawrence Livermore National Lab',
 'Leidos',
 'Lendio',
 'Liberty Mutual Insurance',
 'Life360',
 'LifeOmic',
 'Lightspeed Systems',
 'LinQuest',
 'Lorven Technologies Inc',
 'MILVETS Systems Technology, Inc.',
 'MIT Lincoln Laboratory',
 'MITRE',
 'Mackin',
 'Magna International Inc.',
 'ManTech',
 'Market America Inc',
 'Mars',
 'MassMutual',
 'Mathematica Policy Research',
 'Maven Wave Partners',
 'Maxar Technologies',
 'Maxiom',
 'Mentor Graphics',
 'Meridian Knowledge Solutions',
 'Merrick Bank',
 'Metromile',
 'Metronome, LLC',
 'Microagility',
 'Midland Credit Management',
 'MoTek Technologies',
 'Monte Rosa Therapeutics',
 'Montway Inc',
 'Moxie Software',
 'Mteq',
 'Murray Resources',
 'NAVEX Global',
 'NYSTEC',
 'Natera',
 'Navio',
 'Navy Federal Credit Union',
 'Net2Source Inc.',
 'Netskope',
 'New England Biolabs',
 'New Iron Group, Inc.',
 'New Relic',
 'New York Technology Partners',
 'Noblis',
 'Nolij Consulting',
 'Notion Labs',
 'Novartis',
 'Novetta',
 'Ntrepid',
 'NuWave Solutions',
 'Numeric, LLC',
 'Object Partners',
 'Offerpad',
 'Old World Industries',
 'OneMagnify',
 'Opendoor',
 'OppLoans',
 'Oshkosh Corporation',
 'Ovative Group',
 'Oversight Systems',
 'PETADATA',
 'PNNL',
 'PROPRIUS',
 'Pacific Northwest National Laboratory',
 'Pactera Edge',
 'Paige',
 'Parker Hannifin',
 'PayPal',
 'PeopleCom',
 'Peraton',
 'Perspecta',
 'Pfizer',
 'Phantom AI',
 'Phoenix Operations Group',
 'Photon Infotech',
 'Plymouth Rock Assurance',
 'Point72 Ventures',
 'Postmates - Corporate HQ',
 'Powertek',
 'Pragmatics, Inc.',
 'Praxis Engineering',
 'Predictive Research Inc',
 'Procore Technologies',
 'Progress Rail, A Caterpillar Company',
 'Protolabs',
 'Puget Sound Energy',
 'PulsePoint',
 'QOMPLX',
 'Quartet Health',
 'Quest Integrity',
 'Quick Base',
 'Qurate Retail Group',
 'REE',
 'Radiant Digital',
 'Radical Convergence',
 'Rainmaker Resources, LLC',
 'Rapid Value Solutions',
 'Relativity',
 'Resurgent Capital Services',
 'Reynolds American',
 'Rincon Research Corporation',
 'Ritedose',
 'Riverside Research Institute',
 'Robert Half',
 'Roche',
 'Rocket Lawyer',
 'Royce Geospatial',
 'Rubius Therapeutics',
 'SAIC',
 'SPECTRUM',
 'SSATI',
 'Sage Intacct',
 'Sandhills Global',
 'Sandia National Laboratories',
 'Sanofi',
 'Scoop',
 'Security Finance Corporation of Spartanburg',
 'Shape Security',
 'Sharpedge Solutions Inc',
 'Shelter Insurance',
 'Shimento, Inc.',
 'ShorePoint',
 'SkillSoniq',
 'SleePare',
 'Smith Hanley Associates',
 'Software Engineering Institute',
 'SolutionIT, Inc.',
 'Solving IT International Inc',
 'Sonde Health',
 'Sophinea',
 'Southwest Research Institute',
 'Spectrum Communications and Consulting',
 'Sprezzatura Management Consulting',
 'Spring Health',
 'State of Virginia',
 'Stratagem Group',
 'Stride Search',
 'Stripe',
 'Summa Health System',
 'Surya Systems',
 'Swiss Re',
 'Systems & Technology Research',
 'T. Rowe Price',
 'TA Digital',
 'TACG Solutions',
 'TBWA\\Chiat\\Day',
 'TE Connectivity',
 'TECHNOCRAFT Solutions',
 'TRANZACT',
 'Take-Two',
 'Takeda',
 'TechProjects',
 'Tecolote Research',
 'Temboo',
 'Tempo Automation',
 'Tempus Labs',
 'The Buffalo Group',
 'The Davey Tree Expert Company',
 'The Drive Media, Inc.',
 'The Knot Worldwide',
 'The Mom Project',
 'The Trade Desk',
 'ThreeBridge Solutions',
 'Thumbtack',
 'Tivity Health',
 'Tokio Marine HCC',
 'Tower Health',
 'Trace Data',
 'TransVoyant',
 'Travelers',
 'Trexquant Investment',
 'Trident Systems Inc',
 'Triplebyte',
 'Trovetechs Inc',
 'TrueAccord',
 'Twitch',
 'Twitter',
 'Two95 International Inc.',
 'Tygart Technology, Inc',
 'US Pharmacopeia',
 'USAC',
 'USI',
 'UST Global',
 'Underwriters Laboratories',
 'Unicom Technologies INC',
 'United BioSource',
 'Upside Business Travel',
 'Upstart',
 'VANTA Partners',
 'VBeyond Corporation',
 'Via Transportation',
 'Visionary Integration Professionals',
 'Visionist, Inc.',
 'Voice',
 'WCG (WIRB-Copernicus Group)',
 'WGSN',
 'Werner Enterprises Inc',
 'Western Digital',
 'XPO Logistics',
 'XSELL Technologies',
 'Xator Corporation',
 'bioMérieux',
 'eBay',
 'hc1',
 'iRobot',
 'iSeatz',
 'webfx.com']

In [ ]:
print(sorted(df.Rating.unique()))

[np.float64(2.0), np.float64(2.1), np.float64(2.2), np.float64(2.3), np.float64(2.4), np.float64(2.5), np.float64(2.6), np.float64(2.7), np.float64(2.8), np.float64(2.9), np.float64(3.0), np.float64(3.1), np.float64(3.2), np.float64(3.3), np.float64(3.4), np.float64(3.5), np.float64(3.6), np.float64(3.7), np.float64(3.8), np.float64(3.9), np.float64(4.0), np.float64(4.1), np.float64(4.2), np.float64(4.3), np.float64(4.4), np.float64(4.5), np.float64(4.6), np.float64(4.7), np.float64(4.8), np.float64(4.9), np.float64(5.0), np.float64(nan)]

In [ ]:
sorted(df['Rating'].unique())

df['Rating'] = np.where(df['Rating'] == -1,0,df['Rating'])
print(sorted(df.Rating.unique()))

[np.float64(2.0), np.float64(2.1), np.float64(2.2), np.float64(2.3), np.float64(2.4), np.float64(2.5), np.float64(2.6), np.float64(2.7), np.float64(2.8), np.float64(2.9), np.float64(3.0), np.float64(3.1), np.float64(3.2), np.float64(3.3), np.float64(3.4), np.float64(3.5), np.float64(3.6), np.float64(3.7), np.float64(3.8), np.float64(3.9), np.float64(4.0), np.float64(4.1), np.float64(4.2), np.float64(4.3), np.float64(4.4), np.float64(4.5), np.float64(4.6), np.float64(4.7), np.float64(4.8), np.float64(4.9), np.float64(5.0), np.float64(nan)]

In [ ]:
df

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Updated Job Title,Min Salary,Max Salary,Average Salary
0,0,Sr Data Scientist,137000-171000,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993.0,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",Data scientist,137000,171000,154000
1,1,Data Scientist,137000-171000,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968.0,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),NaN,Data scientist,137000,171000,154000
2,2,Data Scientist,137000-171000,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981.0,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),NaN,Data scientist,137000,171000,154000
3,3,Data Scientist,137000-171000,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000.0,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",Data scientist,137000,171000,154000
4,4,Data Scientist,137000-171000,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998.0,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",Data scientist,137000,171000,154000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,105000-167000,Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989.0,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,NaN,Data scientist,105000,167000,136000
668,668,Data Scientist,105000-167000,Job Description\nBecome a thought leader withi...,NaN,JKGT,"San Francisco, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data scientist,105000,167000,136000
669,669,Data Scientist,105000-167000,Join a thriving company that is changing the w...,NaN,AccessHope,"Irwindale, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data scientist,105000,167000,136000
670,670,Data Scientist,105000-167000,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,NaN,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),NaN,Data scientist,105000,167000,136000
671,671,Data Scientist,105000-167000,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976.0,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),NaN,Data scientist,105000,167000,136000

In [ ]:
import pandas as pd
import plotly.express as px

# The dataframe `df` is already loaded and cleaned from previous steps.
# We will use the existing `df` directly.

# Calculate the average salary for each 'Updated Job Title'
avg_salary_by_job = df.groupby('Updated Job Title')['Average Salary'].mean().reset_index()

# Remove the 'na' category from the aggregated data
avg_salary_by_job = avg_salary_by_job[avg_salary_by_job['Updated Job Title'] != 'na']

# Create bar chart
fig = px.bar(
    avg_salary_by_job,
    x="Updated Job Title",
    y="Average Salary",
    color="Updated Job Title",
    labels={
        "Updated Job Title": "Job Title",
        "Average Salary": "Average Salary ($)"
    },
    title="Average Salary by Job Title (Excluding 'na' Category)",
    hover_data=["Updated Job Title", "Average Salary"]
)

# Add maximum value at the top of each bar
for i, row in avg_salary_by_job.iterrows():
    fig.add_annotation(
        x=row["Updated Job Title"],
        y=row["Average Salary"],
        text=f"${row['Average Salary']:.0f}",
        showarrow=False,
        yshift=10
    )

# Improve layout
fig.update_layout(
    legend_title_text="Job Title",
    template="plotly_white"
)

fig.show()

In [ ]:
import plotly.io as pio

# Define the output path in Google Drive
output_html_path = '/content/drive/MyDrive/Colab Notebooks/average_salary_by_job_title.html'

# Save the figure as an HTML file
fig.write_html(output_html_path, auto_open=False)

The interactive bar chart has been saved as an HTML file to your Google Drive at `/content/drive/MyDrive/Colab Notebooks/average_salary_by_job_title.html`. You can now open this file in a web browser for your presentation.

The interactive bar chart has been saved as an HTML file to your Google Drive at `/content/drive/MyDrive/Colab Notebooks/average_salary_by_job_title.html`. You can now open this file in a web browser for your presentation.

In [ ]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/cleaned_ds_jobs.csv', index=False)

The cleaned data has been saved to your Google Drive as `cleaned_ds_jobs.csv`.